# Generated by Django 4.1.7 on 2023-02-27 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_alter_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='stars',
            field=models.IntegerField(choices=[(1, '*'), (2, '* * '), (3, '* * * '), (4, '* * * * '), (5, '* * * * * ')], default=1),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.director'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_rewiews', to='movie_app.movie'),
        ),
    ]
