# Generated by Django 4.1.7 on 2023-02-28 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_alter_movie_directors'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_id', to='movie_app.movie')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_id', to='movie_app.reviews')),
            ],
        ),
    ]
